### ISSUE TITLE
Where to move libnvinfer.so.7.0.0.1

### ISSUE THREAD

**Issue by makaveli10** [NVIDIA-AI-IOT/deepstream_tlt_apps#12]
Systems GPU_ARCHS => 75 (x =7, y= 5)
and the plugin that is already present in /usr/lib/x86_64-linux-gnu => libnvinfer_plugin.so, libnvinfer_plugin.so.7, libnvinfer_plugin.so.7.0.0

Generated files : libnvinfer_plugin.so  libnvinfer_plugin.so.7.0.0  libnvinfer_plugin.so.7.0.0.1
The question is:
1. Do I need to move the plugin that is already present "libnvinfer_plugin.so.7.0.0"  and back it up (or backup all the libnvinfer_plugin.so*)? It is confusing because  it is mentioned in the readme to back up libnvinfer_plugin.so.7.x.y(x=7,y=5) which is not here !!

2. There are the lib files generated => libnvinfer_plugin.so, libnvinfer_plugin.so.7.0.0 and libnvinfer_plugin.so.7.0.0.1. Which one of the generated files to copy(or to copy all) to '/usr/lib/x86_64-linux-gnu' and as what libnvinfer_plugin.so.7.0.0 or libnvinfer_plugin.so.7.7.5.. It's not that clear from the README.

**Comment by mchi-zg** [comment]
Sorry for confusion!

1. the x and y in libnvinfer_plugin.so.7.x.y  have nothing do to with the  GPU_ARCHS, they just to indicates the suffix number could be different.
After you build TensorRT OSS and generated the multiple  libnvinfer_plugin.so* files as you mentioned, you only need to replace the real file libnvinfer_plugin.so.7.0.0  with libnvinfer_plugin.so.7.0.0.1, and don't touch the link files.

/usr/lib/x86_64-linux-gnu# ls -l libnvinfer_plugin*
lrwxrwxrwx 1 root root      26 Dec 17  2019 libnvinfer_plugin.so -> libnvinfer_plugin.so.7.0.0
lrwxrwxrwx 1 root root      26 Dec 17  2019 libnvinfer_plugin.so.7 -> **libnvinfer_plugin.so.7.0.0**
-rw-r--r-- 1 root root 6134400 Dec 17  2019 **libnvinfer_plugin.so.7.0.0**
-rw-r--r-- 1 root root 7582056 Dec 17  2019 libnvinfer_plugin_static.a


I'll update the README.

Thanks!
