### ISSUE TITLE
Faster RCNN on Deepstream 5.0

### ISSUE THREAD

**Issue by ishangupta3** [NVIDIA-AI-IOT/deepstream_tlt_apps#2]
I successfully installed deepstream -5.0 on my Jetson Nano. I have also trained a faster rcnn model using TLT 2.0 and generated the appropriate .engine file.

My goal is to deploy it using deepstream 5.0, i am following the instructions here to install the respective pre requisites:
https://docs.nvidia.com/metropolis/TLT/tlt-getting-started-guide/#intg_fasterrcnn_model

The 2 pre requsities were installing the custom parsers which i successfully did using this repository (the metropolis documentation mentioned a link to gitlab which is broken) and the other one is downloading the Tensor RT open source to get the custom plugins specifically: cropandresize plugin and the proposal plugin.

So, I am trying to install this as mentioned onto my jetson nano:
https://github.com/NVIDIA/TensorRT

It is not installing at all; any help is greatly appreciated.

**Comment by mchi-zg** [comment]
"It is not installing at all"  ==> what failure ?  And, as mentioned, for frcnn, it does not need to install https://github.com/NVIDIA/TensorRT

**Comment by ishangupta3** [comment]
In the tlt-getting started guide it mentions that this library is a pre-req to deploy frcnn on deepstream 5.0:

**Prerequisite for FasterRCNN model:**
FasterRCNN requires the cropAndResizePlugin and the proposalPlugin. This plugin is available in the TensorRT open source repo, but not in TensorRT 7.0. Detailed instructions to build TensorRT OSS can be found in TensorRT Open Source Software (OSS).

https://docs.nvidia.com/metropolis/TLT/tlt-getting-started-guide/#intg_fasterrcnn_model

**Comment by mchi-zg** [comment]
I'll check with TLT team internally.
But, did you try to run the FasterRCNN without https://github.com/NVIDIA/TensorRT?

**Comment by ishangupta3** [comment]
Hello @mchi-zg - yes i did and the results are not accurate at all, I used the same model and ran inference on tlt 2.0 and got perfect results, meanwhile my results on deepstream 5.0 is attached using faster rcnn :


![deepstream-infer](https://user-images.githubusercontent.com/8518915/81461698-6a08b700-9162-11ea-9a73-d57653d107a6.jpeg)

**Comment by mchi-zg** [comment]
Hi，
Firstly, let's close the fisrt question, FasterRCNN doesn't need https://github.com/NVIDIA/TensorRT, do you agree?  Can we close this question firstly?

**Comment by ishangupta3** [comment]
The documentation explicitly mentions that it does:

Prerequisite for FasterRCNN model

FasterRCNN requires the cropAndResizePlugin and the proposalPlugin. This plugin is available in the TensorRT open source repo, but not in TensorRT 7.0. Detailed instructions to build TensorRT OSS can be found in TensorRT Open Source Software (OSS).

Perhaps that's why there is so much error during inference.

**Comment by mchi-zg** [comment]
No. The accuracy is not related to TensorRT OSS plugin.

Could you list the cases which have good accuracy and which has bad accuracy?

**Comment by ishangupta3** [comment]
When I run inference using the docker container that runs TLT 2.0 - I am getting perfect bounding boxes. When I use that exact video to do inference on deepstream 5.0, I get the results as above.

**Comment by mchi-zg** [comment]
As you can see in the frcnn_labels.txt under nvdsinfer_customparser_frcnn_tlt folder, the trained model does not support the object in this video

**Comment by ishangupta3** [comment]
I trained my own custom model on tlt 2.0 to detect cardboard boxes; and I created my own labels.txt file as well and edited the config files to match my needs. I am using my own custom .engine file as well. The inaccuracy is coming from the a missing plugin, were you successful in running a frcnn model without the open source tensor rt. There is something wrong internally.

**Comment by mchi-zg** [comment]
>> The inaccuracy is coming from the a missing plugin, were you successful in running a frcnn model without the open source tensor rt?
Certainly

**Comment by ishangupta3** [comment]
What do you believe could be the issue for my very inaccurate inference on deepstream 5.0?

**Comment by mchi-zg** [comment]
Let me recap the info below, please check if my understanding is right.
1. you trained a model with TLT2.0
2. you tested the model with TLT2.0, the accuracy is perfect
3. you generate a TRT engine
4. you used this TRT engine in this sample and do the inference, the input is (JPEG? video?) , and get inaccurate result.

**Comment by MannySG** [comment]
Yes that is correct.

**Comment by ishangupta3** [comment]
Yes that is correct and specifically the model was frcnn.

**Comment by mchi-zg** [comment]
Not sure if it's ok to share us the model and the test picture so that we can take a try..thanks!

**Comment by ishang3** [comment]
Yes it is possible, I have placed all the necessary files to run on deepstream inside of a google drive folder - can I send it directly to your email if possible?

**Comment by ishangupta3** [comment]
Yes it is possible, I have placed all the necessary files to run on deepstream inside of a google drive folder - can I send it directly to your email if possible?

**Comment by ishangupta3** [comment]
@mchi-zg Just wanted to follow up and know if you need anything else from my side

**Comment by PythonImageDeveloper** [comment]
Hi @ishangupta3 ,
Is it possible to share your experience How you trained the model with TRT and then run on jetson nano. How to to install DeepStream5 on jetsno nano.
How to run TLT docker image in PC?
I'm new in this work,any help is greatly appreciated.

**Comment by mchi-zg** [comment]
Hi @ishangupta3 
We can reproduce the issue with the file provided, we are looking into it, will get back to you once we have any progress, thanks for your patience.  

Hi @PythonImageDeveloper 
You could file a topic in NVIDIA DeepStream forum - https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/deepstream-sdk/15 , we will give you answer. But actually, there are many simialr quetions asked in the forum, you could search or read DS doc to get some answers.

**Comment by zhimengf** [comment]
@ishangupta3 Can you please also share the TLT training experiment_spec file with us so we can check to see if the TLT spec file aligns with the DS config file from our side?

**Comment by ishangupta3** [comment]
@zhimengf unfortunately I do not have access to the spec file anymore, but I did just make slight changes to the default fastercnn default spec file provided in the docker container.

**Comment by ishangupta3** [comment]
@PythonImageDeveloper the forum is a great place to ask questions and there is also a separate forum for the transfer learning toolkit as well:

My recommendation is to start with the documentation, and go line by line and understand every word

https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/transfer-learning-toolkit/17

**Comment by ersheng-ai** [comment]
@ishangupta3 Problem is solved after updating 2 files:

* **pgie_frcnn_tlt_config.txt:**
Change `num-detected-classes=2` to `num-detected-classes=3`
* **labels.txt:**
Add label `background`

![out_customer_3cls](https://user-images.githubusercontent.com/62684483/82414869-4884c500-9aaa-11ea-8fd8-6e95b55bcd26.jpg)

**Comment by ishangupta3** [comment]
Thank you @ersheng-ai @mchi-zg @zhimengf for all your help.

**Comment by PythonImageDeveloper** [comment]
@ishangupta3 
Excellent,
Is it possible to run your trained model on deep stream sample code? I don't want to use all deep stream sdk on jetson nano.

**Comment by ishangupta3** [comment]
@PythonImageDeveloper 

I recommend using first detectnet V2 model as it is more straightforward in getting set up. They should have a sample directory there which contains the models and config files to get started. 

After training your model in Nvidia Transfer Learning toolkit, it converts the file into .etlt file which basically stands for encrytped tlt file (i believe). You take this file and run it in deepstream, and the very first time it will convert it into a .engine file, this new file is optimized to run on your desired hardware. Then you can ignore the .etlt file and only use .engine file for running inference, and you update your config files respectively. 

The .bin file is optional, it depends in which the mode was converted into. 

I recommend running an example first on deepstream, then after you have an example working fine, then start experimenting further.

**Comment by PythonImageDeveloper** [comment]
Thanks @ishangupta3 
I want to know, you run c++ code for inference or python?

**Comment by ishangupta3** [comment]
I am currently running the c++ deepstream sdk, but they do have python bindings available but I have not used it.

**Comment by PythonImageDeveloper** [comment]
@ishangupta3 
How you get libnvds_infercustomparser_frcnn_tlt.so ? Is it need like this file for detectnet-v2?

**Comment by ishang3** [comment]
For detectnet v2 it is not needed; but for other models like ssd or faster rcnn they are? I recommend first doing an experiment with detectnetv2 then moving onto the other models.

Are you using a Jetson Nano?

**Comment by PythonImageDeveloper** [comment]
@ishangupta3 @ishang3 
Yes I use jetson nano,
My desktop host has gtx 1080, and trained the model with docker TLT, when I want to use **tlt-export** for generating the etlt model with fp16 mode, I get a error for doesn't support fp16 with this platform, I think my gtx 1080 doesn't support fp16, How you converted the trained model to fp16 for jetson nano?

**Comment by ishang3** [comment]
I have used fp32 to export and it works fine on the jetson nano. Have you tried that?
